// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCY78U2hGYSU_fEU5Lk-yHqnMaF-GyILbs',
//     appId: '1:771606205051:web:eee22c0387eafbf91e48de',
//     messagingSenderId: '771606205051',
//     projectId: 'dukkan-v3',
//     authDomain: 'dukkan-v3.firebaseapp.com',
//     storageBucket: 'dukkan-v3.appspot.com',
//     measurementId: 'G-LN1R8FJTXK',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAYkjyOFGUeeBw6SUszW-4i_srq0EDZS1E',
//     appId: '1:771606205051:android:86c1861f2a3199271e48de',
//     messagingSenderId: '771606205051',
//     projectId: 'dukkan-v3',
//     storageBucket: 'dukkan-v3.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBo00QEVUOg1k7TVZzMLMjOFgZNwq62Bqo',
//     appId: '1:771606205051:ios:65e84709b32fb8cb1e48de',
//     messagingSenderId: '771606205051',
//     projectId: 'dukkan-v3',
//     storageBucket: 'dukkan-v3.appspot.com',
//     iosBundleId: 'com.example.dukkan',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBo00QEVUOg1k7TVZzMLMjOFgZNwq62Bqo',
//     appId: '1:771606205051:ios:9fc55b85150df84a1e48de',
//     messagingSenderId: '771606205051',
//     projectId: 'dukkan-v3',
//     storageBucket: 'dukkan-v3.appspot.com',
//     iosBundleId: 'com.example.dukkan.RunnerTests',
//   );
// }
